# Generated by Django 3.1.3 on 2020-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Draft'),
        ),
    ]
