# Generated by Django 3.1.3 on 2020-11-13 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201113_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment_like',
            unique_together={('author', 'comment')},
        ),
    ]
