# Generated by Django 3.1.3 on 2020-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201127_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_setting',
            name='allow_discussion',
            field=models.BooleanField(verbose_name='Discussion'),
        ),
        migrations.AlterField(
            model_name='post_setting',
            name='show_author_name',
            field=models.BooleanField(verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='post_setting',
            name='show_created_at',
            field=models.BooleanField(verbose_name='Show Create Date'),
        ),
    ]
