# Generated by Django 3.1.3 on 2020-12-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201202_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='confirm'),
        ),
    ]
